### ISSUE TITLE
Item stack issue 

### ISSUE THREAD

**Issue by Shibva** [Alexthw46/Hexblades#3] opened 2021-11-07 22:26 UTC
idk why this is the case but when you kill a mob using the blades (or in this specific case, the twin dagers, level 1) sometimes some of the items that are dropped when using them dont stack with others that might exist when you killed things without them

the reason for this is because of these items that sometimes drop have NBT data applied to them for some reason, so a fix to this would be to simply make sure that mob usual mob drops have their NBT data wiped, but to be sure, it should be made to only do such unless the item has some from of invintory nbt or enchantment NBT data

**Comment by Alexthw46** [comment] 2021-11-08 04:36
With only these infos, I'm pretty clueless. First which version are you on,the new beta or older? 
Second, does it only applies to the twins?
Third, can you manage to use a nbt explorer (iirc that's their name) to see which kind of tag the items have? 

I shouldn't be altering drops, the only clue could be the custom effect that is applied when you hit with the left dagger.

**Comment by Alexthw46** [comment] 2021-12-23 10:30
The bug should be fixed in 0.9, it wasn't affecting the drops but items held while the hexblade was out of power due to a very old error. It would have been found quicker with the nbt check.
If that was another bug and it shall happen again, open a new issue.

**Closed as completed by Alexthw46** 2021-12-23 10:30 UTC
Labels: incomplete

**Comment by Shibva** [comment] 2021-12-23 16:20
just woke up and aw this, I also have another bug related to this, idk if it will be fixed in this pix here as a side result, but if a hexblades change runs out and your not holding it, the item you have will unusuable till you go back to sed depleded hexblade to inniate the item recharge

**Comment by Alexthw46** [comment] 2021-12-23 16:23
yes, it's fixed in the newest. Same root cause
